Measurement and Province Selection Page
HOLOS-International-Solutions/HOLOS-Intl pull request #10
Opened 2024-09-24 14:29 UTC by ShakeefAhmedRakin

2024-10-20 14:56 UTC, ShakeefAhmedRakin commented
### PR Summary: Measurement and Province Selection Page Implementation With Dynamic Province Enumeration

This branch focuses on creating the **Measurement and Province Selection** page with dynamic province population based on country version. Key changes include:

- **New Page Creation**: Added the `MeasurementProvince` page with dropdowns for measurement and province selection, and added navigation logic.
- **Dependency Injection**: `MeasurementProvinceViewModel` and `MeasurementProvinceView.axaml.cs` was refactored to properly implement DI for `IRegionManager` and `ICountrySettings`.
- **Province Enumeration**: Setup `ProvinceService` to dynamically populate province options based on `CountryVersion`.
- **Navigation**: Implemented navigation from the Disclaimer View to the MeasurementProvince View, and onwards to a blank page for future content.
- **Enum Binding**: Recreated the MeasurementProvince Selection View and ViewModel with proper enumeration bindings for selection.

2024-10-20 18:54 UTC, holos-aafc commented on H.Core/Enumerations/Province.cs
> +        [LocalizedDescription("EnumSelectProvince", typeof(Resources))]
Nice work following conventions in naming the resource keys. All the enum resource keys I created should all have the prefix 'Enum'_stringName. Good job!

2024-10-20 18:59 UTC, holos-aafc commented on H.Core/Services/Provinces/IProvinces.cs
> +        IEnumerable<object> GetProvinces();
This is a nice definition of an interface. Simple and to-the-point. It generally a better idea to use strongly typed type paratmeters instead of object. This is challenging to do here since we are using enums but generally the type parameters should be something other than 'object'. We can discuss this at our next meeting.

2024-10-20 18:59 UTC, holos-aafc commented on H.GUI.Avalonia/H.Avalonia/App.axaml.cs
> +            containerRegistry.RegisterForNavigation<BlankView, BlankViewModel>();
Nice. We can start to use this registration as our new 'home page'

2024-10-20 19:01 UTC, holos-aafc commented on H.GUI.Avalonia/H.Avalonia/ViewModels/BlankViewModel.cs
> +    public class BlankViewModel : BindableBase
We can inherit from ViewModelBase instead of BindableBase since ViewModelBase also inherits from BindableBase

2024-10-20 19:04 UTC, holos-aafc commented on H.GUI.Avalonia/H.Avalonia/ViewModels/SupportingViews/MeasurementProvince/MeasurementProvinceViewModel.cs
> +            _regionManager = regionManager;
Typically there are guards placed in the view model constructors to guard against someone placing/injecting null objects. 

e.g.

`if(regionManager != null){
_regionManager = regionManager;
}
else{
throw new ArgumentNullException(nameof('regionManager')
}`

2024-10-20 19:05 UTC, holos-aafc commented on H.GUI.Avalonia/H.Avalonia/ViewModels/SupportingViews/MeasurementProvince/MeasurementProvinceViewModel.cs
> +            _selectedProvince = ProvinceCollection.FirstOrDefault() ?? new object();
It would be best for us to find a solution where we do not create generic objects. Using strongly typed classes, interfaces, etc. is the better approach. i.e. `?? new ProvinceTypeOrSomething()`

2024-10-20 19:07 UTC, holos-aafc commented on H.GUI.Avalonia/H.Avalonia/Views/SupportingViews/MeasurementProvince/MeasurementProvinceView.axaml
> +		<StackPanel Grid.Row="1" Grid.Column="1" HorizontalAlignment="Center" VerticalAlignment="Center" Spacing="10">
We can begin to start using Styles for things such as Spacing="10", etc. Styles are similar to CSS and will save us a lot of time if we can apply styles to elements instead of specifying "Spacing=10" for all elements.

2024-10-20 19:08 UTC, holos-aafc commented on H.GUI.Avalonia/H.Avalonia/Views/SupportingViews/MeasurementProvince/MeasurementProvinceView.axaml.cs
> +            if (measurementProvinceViewModel != null)
Nice usage of guard statements here. This prevents null objects from being used and possible dereferencing a null reference at runtime.

2024-10-20 19:09 UTC, holos-aafc requested changes
Excellent work so far!

I have provided some inline comments in the changed files that we can discuss at the next meeting.

One note about the order of enumerations. It is important to keep the order of the entries in the enum the same and not change the ordering since the saved session data will depend on the numerical ordering in the enum files to be non-changing. This is why it is also important to add addtional enum values to the end of the enum file (not inbetween other entries or at the start of the file.

Overall this is an excellent commit!

2024-10-21 16:35 UTC, Badhansen commented
Thanks @ShakeefAhmedRakin. Merging this PR.

2024-10-21 16:35 UTC, merged